spring.application.name=authservice


# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service
spring.datasource.username=${pgUsername}
spring.datasource.password=${pgPassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#jwt
spring.app.jwt-secret = ${jwt_secretKey}

